# Generated by Django 5.2.12 on 2026-03-27 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_restored_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Uploaded image file for the property.', upload_to='property_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Optional alt text for accessibility and SEO.', max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates if this image is the main display image.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order in which images are displayed.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='Property to which this image belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_restored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['property'], name='core_proper_propert_2b6375_idx')],
            },
        ),
    ]
