# Generated by Django 5.2.12 on 2026-03-27 04:17

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(help_text='Uploaded image file for the property.', upload_to=utils.helper.upload_to_model_folder),
        ),
    ]
